### ISSUE TITLE
Move to GHE

### ISSUE THREAD

**Issue by kpodonog** [usdhs/nimbus#2]
This team has repositories in uscis/github.com that are inactive.  In an effort to maintain an accurate account of users and private repositories for licensing purposes,  please review your repositories then move any required data to GHE(  https://git.uscis.dhs.gov/) as necessary.

Eliminate unused repositories by October 6th 2017.  
Repositories that have remained inactive for more than 60 days will be removed from uscis/github.com.
@USCIS/elis-dev  @USCIS/usds

**Comment by brodygov** [comment]
Frankly this push to move open source repos to GHE is ridiculous and runs counter to OMB policy. I've moved this repo to github.com/usdhs/nimbus and made it again public, since USCIS seems so far unable to comply with OMB M-16-21.

https://sourcecode.cio.gov/
